{% set name = "ubiquerg" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa3a81e2310f548713101d9fe3293c1673eaeb7361401d22b51297181bd937a0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ubiquerg

about:
  home: https://github.com/pepkit/ubiquerg
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Various utility functions.

extra:
  recipe-maintainers:
    - stolarczyk
